### ISSUE TITLE
GPU acceleration

### ISSUE THREAD

**Issue by xg320** [techjarves/USB-Uncensored-LLM#27]
What about GPU support? Running llm using CPU is very-very slow.

**Comment by alosborne11-del** [comment]
I also had issues with GPU not being used. 
Asked Deep Seek and whipped up a solution no worries just copy the details in the Power Shell terminal and ask for a solution.
Worked for me and I am retarded.
